### ISSUE TITLE
 New features: Match peaks

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#10]
It would be helpful to clarify how peak heights are matched, and thus whether matching the ‘heights’ of the peaks has other effects on the fitness landscape.  For example, if peak matching is equivalent to adding a scalar to all fitness values, might this mean that rescaling an initially flatter landscape results in all areas having a higher mean fitness?  Or if peak scaling corresponds to a multiplication, may scaling result in a more uneven fitness landscape?  My guess is that neither of these is a good characterization of what's actually happening, but again, I think a reader should be able to form a general picture of what the software is doing from the manuscript, and be able to grasp whether the mechanism of ensuring that peaks match might influence the progress or character of simulations.

**Comment by RussellGarwood** [comment]
This is actually done using the nature of the fitness algorithm - if you keep the same patterns of zeros and ones across masks overall, but shuffle their position site-wise, you will end up with the same peak fitness, but within each environment, and different genome to achieve that peak fitness. I have done my best to explain this - including an example - in the manuscript, as per above commit.
