### ISSUE TITLE
Contribution and authorship: Acknowledging contributions

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#14]
Re: https://github.com/openjournals/joss-reviews/issues/6722

Individuals' contributions to the project are acknowledged in the Author Contributions section of the manuscript, which is sufficient.  

To adopt best practice and make contributions across all versions of the software more explicit (and machine readable), you might consider including a `codemeta.js` file https://codemeta.github.io/codemeta-generator/ .
R packages use a [contribution taxonomy](https://www.loc.gov/marc/relators/relaterm.html) to identify the nature of contributors' roles in the project.

**Comment by RussellGarwood** [comment]
Thanks for this suggestion. I had not come acxross a codemeta.js file before - looks like a great idea. I will generate one as soon as the JOSS paper is published, thus allowing me to link the codemeta.js file to the JOSS contribution. To this end I'll be keeping this issue open until that is included

**Comment by RussellGarwood** [comment]
Thanks again for this suggestions @ms609 - sadly my coding time has been limited since the start of september due to teaching, but with the above push I have just included a codemeta.json. A great tool!
