### ISSUE TITLE
Abort run in progress

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#17]
Once I start a run, I see an option to pause, but not to abort the run.   It feels like it would be useful to be able to terminate a long run before it completed in order to modify settings and restart the run, without closing the software and opening a new instance (and losing Simulation Settings in the process).

**Comment by RussellGarwood** [comment]
Yes, I agree @ms609 - to the extent that this does actually exist (just hit escape for an abort). Obviously this needs to be included in the documentation, which I shall do: but I figured I'd not it here now so you're not having to kill the software every time you want to abort a run whilst you're reviewing.

**Comment by ms609** [comment]
Useful to know, thank you!  Perhaps adding a button to the GUI would also help to maximise the visibility of the function?

**Comment by ms609** [comment]
And as a related issue – I can't see a way to abort the "Fitness histogram" calculation – even if I quit the TREvoSim GUI the calculation seems to continue running in the background.

**Comment by RussellGarwood** [comment]
Yes, good shout on the Fitness histogram - I'm not sure how I missed that. After the above commits, both fitness histogram, and a simulation, now have a stop button in the toolbar that functions identically to the escape button (and you can now pause fitness histogram too).
