### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#25]
Now that I have Qt configured correctly (#15) I'm able to start the build process.

However, when I build the release version of TREvoSim

![image](https://github.com/palaeoware/trevosim/assets/1695515/b3d0b928-817b-47c7-b6aa-6d4a5e431fa7)

I see a few thousand errors:
![image](https://github.com/palaeoware/trevosim/assets/1695515/5d40a793-8515-48e3-8beb-afc928ca2bc8)

I've confirmed that Ninja is on the path.

**Comment by alanspencer** [comment]
You are not using the VisualStudio 2019 Toolkit, currently you are trying to use a MinGW 64-bit kit. You can see which kit is currently setup for each project under the 'Kit' part of the build button pop out dialog. Here is mine:

![gI4q1UqHMy](https://github.com/palaeoware/trevosim/assets/1466599/9e0db923-88c2-4d3e-afeb-6151e7550224)

To change the kit go to Projects:

![viYR4N79k1](https://github.com/palaeoware/trevosim/assets/1466599/768a45f7-ef09-46a2-a0da-2a4c95bf93c6)

And select the Desktop Qt 6.7.1 MSVC2019 64bit kit under the 'Build and Run' section:

![peCRMnHzKK](https://github.com/palaeoware/trevosim/assets/1466599/6ed9ee10-2ff0-4390-b212-a71a02f479ba)

**Comment by ms609** [comment]
Success!  I've got the software running, and can build it after making my own edits to the source code.

I guess that this additional step won't apply to all users, but hopefully it is easy to add to the documentation.
