### ISSUE TITLE
Output settings: End of run outputs

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#28]
- [x]  I found the text in the dialog box slightly counterintuitive; on first reading my mind latched onto the "two output files" and I thought that the tree (mentioned twice) had to be one of these.  My suggestion would be to include the two check boxes above rather than below the custom fields, so it's clear that these aren't "afterthoughts"; and to replace the text "File One" and "File Two" with "Custom File 1/2".  I would also consider splitting the long paragraph into a separate chunk of explanatory text associated with each option, so it's obvious that the "also select to have the tree saved as a .nex file" describes the check box, rather than providing a hint as to what a user might type into the Custom Text files.

- The NEXUS template in the custom log 1 box is helpful.
  - [x] Providing an equivalent template for TNT would seem more useful than the existing placeholder text, particularly as TNT's format is less familiar, and particularly if the file is to be written by default.
  - [x] The NEXUS `Begin data` block seems to be missing an `end;` command
  - [x] The use of mixed case conventions (e..g. all caps for ASSUMPTIONS), whilst legal, is confusing 

- [x] The "see documentation" button is a good idea (would it be a useful addition to the "Settings" dialog too?).  Would it make sense for this to link to the "logging" documentation page, rather than the home page?

![image](https://github.com/palaeoware/trevosim/assets/1695515/71a549c9-9cc9-4d47-b371-cff12e0b5fa8)

**Comment by RussellGarwood** [comment]
I think, with above commits, all of the above points in the issue have now been addressed, and documentation updated to reflect the changes.

**Comment by RussellGarwood** [comment]
-- (would it be a useful addition to the "Settings" dialog too?). 

Very good point - implemented with above commit.

I think this is now done, and will close the issue, but do shout if anything needs further attention

**Comment by ms609** [comment]
Looking good; if you're following an Ucfirst convention for the nexus text this should probably include the `End;` commands too?

The "See documentation" buttons in the Simulation Settings dialogs don't work yet (on either tab).  Also note an unfilled `TextLabel` on the Env, ev and play fields settings tab.

**Comment by RussellGarwood** [comment]
Apologies, these were silly mistakes for me to have missed. All fixed now.
