### ISSUE TITLE
Number of replicates not persistent

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#32]
To put TREvoSim through its paces, I have concocted a small toy exercise that will involve simulating datasets under different parameters and analysing them in R. 

My approach to simulating datasets with different parameters is to manually (programatically) edit the settings XML file and load this in to TREvoSim.  This involves a bit of clicking around (see #31), but is tractable at a small scale.

In this context, it would be helpful if the number of replicates in the "Batch" dialog box was persistent, and better still could be set within the settings file.  This would save modifying the number for each distinct set of parameters.

**Comment by RussellGarwood** [comment]
@ms609 - this is now implemented with above changes, which will hopefully make your life easier for stuff like this. Note that the value defaults to 25 replicates, but if you tell it something else that is persistent, and is now a variable you can set via the xml files. I thought it may be confusing to have the value changed in the settings dialogue too, so I have not added it to that.
