### ISSUE TITLE
"Write file" checkbox not honoured

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#33]
After loading settings from file, I see that"Write file" is unchecked

![image](https://github.com/palaeoware/trevosim/assets/1695515/eb597e89-a54d-476d-9aef-c53775c6253a)

but a batch run creates the corresponding files nonetheless

![image](https://github.com/palaeoware/trevosim/assets/1695515/4c294640-5870-4abb-98de-5a66b86eae4f)

(This affects File One and File Two)

**Comment by RussellGarwood** [comment]
Thanks for catching this - it is now fixed!
