### ISSUE TITLE
Cannot write log files to subdirectories

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#34]
I would like to write the output of a simulation to a subdirectory within TREvoSim_output.  (Windows gets grumpy when there are too many files within a single directory – and it will make my output easier to navigate.)

If I specify a Basename of `dir/file`

![image](https://github.com/palaeoware/trevosim/assets/1695515/e377f31d-91d8-432d-955b-99c12f75ff3f)

I see an error at the end of the run:

![image](https://github.com/palaeoware/trevosim/assets/1695515/b6db223b-841f-4819-a935-84fea1751e1c)

Ideally TREvoSim would create the `dir` subdirectory.  Failing that, it would be helpful to have some input validation so the user sees the error before beginning a run.

**Comment by RussellGarwood** [comment]
I had not considered this before - thanks for the suggestion. Can you clarify, though - I could make the software create dir for you, no worries, but then that would still result in - if you were e.g. doing a batch - a large number of files in that directory, just nested under one TREvoSim output folder. So would it be preferable to add an output option of e.g. "one folder per replicate" or something along those lines?

**Comment by RussellGarwood** [comment]
(sorry, I accidentally closed rather than commenting!)

**Comment by ms609** [comment]
I can see two use cases here:
- General: A user wants to put .nex files in a separate directory to .tnt files
- The one I have in mind: a user will edit a setting, then edit the directory name.  So for example, I have procedurally generated some settings files that set the "number of taxa" option, and I want these files to also set directory names for output that look something like `<NTAXA>_taxa`.

**Comment by RussellGarwood** [comment]
With the above commit this is now implemented - FYI you need to use forward slashes for paths (I note this, because on windows the native separator is a backslash). If you enter a path via the GUI with backslashes, the software replaces this with a forward slash, but if you are loading it programatically, you will need to ensure you use a forward slash otherwise the software will provide an error message. I'll add this to the documentation.
