### ISSUE TITLE
Batch vs run file numbering

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#35]
"Run" and "Batch" behave differently, and thus do not play nicely together.

- "Run" creates a new run, labelled by adding one to the label used the last time "Run" was clicked
- "Batch" creates N new runs, labelled 0 to (N-1).

So clicking Run, Run, Batch(25), Run results in
- run000 - overwritten
- run001 - overwritten
- run000..024 - overwriting run000 and run001
- run002 - overwriting run002 from the batch run.

As overwriting without prompting feels undesirable (and unnecessary), I would consider updating "batch" to behave like "run".   This would also provide an easier way to expand a batch; it seems that at present the only way to expand a batch is to discard previous results and start from scratch.

**Comment by RussellGarwood** [comment]
I've modified the behaviuor to reflecy this (very sensible) suggestion. Thanks. The above will now result in 28 runs written to a file. The only place this may trip up is if a batch is cancelled part way through: I can't easily update the counter on cancel of a parellelised part of the code. This won't cause crashes, but may result in some runs being overwritten.
