### ISSUE TITLE
Software paper: New features

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#4]
Re: https://github.com/openjournals/joss-reviews/issues/6722

- [x] It would make the manuscript easier to follow if the new features were arranged thematically, rather than alphabetically (especially as the “feature names” are somewhat arbitrary).  For example, it would seem natural to group features that enrich the simulation model (Ecosystem engineering, Expanding playing field) separately from those that relate more to the operation of the software (Logging, Codebase Tests – which in any case is already presented out of sequence).

- [x] I would suggest that the description of new features in the text should be self-contained, so that a reader can understand what the features are and what purpose they serve.  Whilst I appreciate that further details are available in the documentation and in related papers, I didn’t find it easy to find this information, and I think it asks a lot of a reader to search for context that could be provided reasonably concisely in the manuscript itself.  

I'll include specific comments on individual sections as individual issues:
- [x] #5 
- [x] #6
- [x] #7
- [x] #8
- [x] #9 
- [x] #10

**Comment by RussellGarwood** [comment]
I've addressed all of the individual "New features" issues linked from this, and in doing so have tried throughout to - whilst thinking of the word limit - also make this all self contained. I hope this has improved the clarity throughout. I have also rearranged the new features as suggested. As ever, feedback welcome, and thanks for the pointers!

**Comment by ms609** [comment]
This looks great – this section now feels coherent and easy to follow, and strikes an excellent balance between brevity and exposition.
