### ISSUE TITLE
Crash when not updating uninformative factor

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#40]
When I load these settings:

[tax20_rate2.51.txt](https://github.com/palaeoware/trevosim/files/15479758/tax20_rate2.51.txt)
> (Uploaded as .txt because GitHub doesn't like the .xml file ending)

Then click "Batch" and select "No" in the "Hmmm" dialog 

![image](https://github.com/palaeoware/trevosim/assets/1695515/9a8db653-61b7-46cd-ab33-726b453b5e44)

TREvoSim freezes.

If I select "Yes", it purrs away happily.

I see the same behaviour if I set the `<stripUninformativeFactor>` setting to a positive number whilst leaving `stripUninformativeFactorSettings` unset.

**Comment by RussellGarwood** [comment]
@ms609 - oof, good catch, this was a silly mistake. If you update the source to include the above commit, this will fix the crash. Based on one of your other comments (thanks!), I shall remove the calculate strip uninformative factor down the line, which will provide a more elegant solution than the last push (but I wanted to start fix this ASAP given it is a segfault).
