### ISSUE TITLE
Test ten todo

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#46]
I notice that the source for testinternal::testTen notes:

> // To do - test coding v.s. non-coding? Needs to be done prior to release, but perhaps this needs a bit of a think of what should be released?

Does this comment still need attention or has the issue been resolved?

**Comment by RussellGarwood** [comment]
That does, thanks for pointing it out. I had previously only tested it using the working log. In the above commit, I have not only expanded the test, but also further granularised how the simulations deals with this process (it took me the best part of an hour to remember how my old code worked, and thus I chose to restructure so if I need to modify again [or someone else wants to modify] the code is a bit clearer). 

Everything did work as expected, and the expanded tests still pass, so all done with this, I think :)
