### ISSUE TITLE
qAsConst deprecated

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#47]
I see that `qAsConst`, used in `simulation.cpp` and `testinternal.cpp`, is deprecated as of QT 6.6; is there an argument for retaining this rather than replacing with (C++17) `std::as_const()`?

```
testinternal.cpp:135:19: 'qAsConst<QList<simulation::playingFieldStructure *>>' is deprecated: Use std::as_const() instead.
:32:1: note: 'qAsConst<QList<simulation::playingFieldStructure *>>' has been explicitly marked deprecated here
```

**Comment by RussellGarwood** [comment]
None! I don't get this warning from my compiler. I shall fix :)

**Comment by RussellGarwood** [comment]
Have done with above commit!
