### ISSUE TITLE
Mac M2 and M3 builds

### ISSUE THREAD

**Issue by RussellGarwood** [palaeoware/trevosim#52]
Add a note to release to reflect likely issues with M2 and M3 chips

**Comment by alanspencer** [comment]
As I'm now back I'll take a look at this issue - I'm sure there is a way to cross-complie btween chipsets and OS versions... we just don't seem to be doing this at the moment. Will try to take a look one evenign this week.

**Comment by RussellGarwood** [comment]
Cool, thanks man :) Code base is changing quite a bit ATM, I'm doing it all on the master branch, FYI - though can of course switch to another branch and start merging if that would make stuff easier on your end.

**Comment by alanspencer** [comment]
Here is a link to a new .dmg host on GoogleDrive that should be a universal MacOS build (arm64 and x86_64). The XCode requiment is set to SDK 13, which should cover all newer MacOS versions (i.e. iOS 15, iPadOS 15, tvOS 15, watchOS 8, and macOS Big Sur 11.3 or above).

https://drive.google.com/file/d/1ud8cXWXtPbKD3BsIvEwHinWhjk5Vnz0y/view?usp=drive_link
