### ISSUE TITLE
Documentation - user manual statement of need, clarity, and example usage 

### ISSUE THREAD

**Issue by atcribb** [palaeoware/trevosim#65]
## Statement of need:
- [x] Does the Statement of need in the software paper need be also put in the user manual? It would fit nicely in the introduction.

## Clarity 

- [x] This is a minor point, but there are some differences in the default settings to the user guide that may just be slightly confusing for a beginner to TREvoSim and simulations in general – Under Settings:Organisms and simulation, ‘Strip uninformative characters via subsampling’ is unchecked in default settings but checked in the user guide 6.0 - Settings - Organisms and simulation

Some slightly confusing wording in the user guide:

- [x]  In 7. Settings – Environment, events and playing fields under EE mode: "...single shot EE, engineers are applied once, half way through a simulation, as outlined above. In contrast, if this radio button is selected, then EE is applied repeatedly after its first application.” From my understanding of the other manuscript, should this read “In contrast, if [the Persistent EE] radio button is selected, then EE is applied repeatedly after its first application”?
- [x] There are also just some minor grammatical errors in EE Frequency and EE mechanism that hinder clarity of these sections.

## Example usage 

- [x] While the quick start is useful in quickly generating output files that the user can take elsewhere for analysis, I’m not sure this classifies as examples that “ideally solve real world problems” as set out in the checklist. Would it be possible to provide a simple but thorough walk through of an example in one of the previously published papers referenced in the user guide? 
- [x] Finally, on a similar note, I think it’s probably worth pointing users somewhere in the direction of how to use their output files (e.g., ape). Speaking from the place of someone who is not primarily a phylogenetics-leaning but still quant palaeo reviewer, I’m just trying to imagine a student or a beginner to this field trying to sink their teeth into TREvoSim and hitting a dead end once they’ve run a simulation but not knowing where to go with their outputs

**Comment by RussellGarwood** [comment]
With the above commits, and a few I accidentally tagged as belong to issue #66 (apologies - you can see those [here](https://github.com/palaeoware/trevosim/issues/66)), I think I have addressed these issues - many thanks indeed for the feedback! The statement of need is now inccluded on the introduction page, as are two new sectioins - one on experimental design, and one on data analysis, to address your example usage points. In both of the latter, I have tried to balance brevity with clarity - in the example usage, full details and lots of discussion are included in the paper, and so I have given the headline points and then where pertinent pointed people towards the paper for more detail. For the analysis section, showing how to use the outputs, I was able to point towards a script that does exactly this in the source code, that I hope will do the job! I also made all the requested edits for clarity (not sure how I left some of the worse bits in those sections slip through!). With that, I think I have addressed these points, but as with the other issue, please do shout if anything else is required and I can reopen the issue.
