### ISSUE TITLE
Software paper - References and general comments 

### ISSUE THREAD

**Issue by atcribb** [palaeoware/trevosim#66]
### References 
- [x] Under section Model enhancements - Ecosystem engineering - Lines 50-51: For a definition of ecosystem engineering, I don’t think Butterfield 2011 is the most appropriate reference, especially as this paper specifically discusses the concept of “evolutionary engineers” that modify much larger scale processes than the new ecosystem engineering features in TREvoSim simulate. I think a more appropriate reference here would be Jones et al. 1994 Oikos, which originally defined ecosystem engineering.

### General clarity 
- [x] Pertaining to Model enhancements - The last sentence in “Playing field mixing” is super useful for explaining the feature in ecological terms. For beginner users, giving examples of each of the model enhancements in these real world ecological/evolutionary/biological terms would be really helpful with the usability of the software (I think I had a similar comment on the other ecosystem engineering manuscript with regard to explaining some of the methodology in eco-evo language)

**Comment by RussellGarwood** [comment]
Thanks for these points, much appreciated. With the above commits I have:

- Updated the EE definition as requested
- For all new features that are not software enhancements, tried to include a brief overview of real world situations these couuld be useful for investigating
- And generally cleaned up the manuscript a little!

Attached is a copy of the PDF of the paper for reference after these changes to save generating another in the review thread!
[paper.zip](https://github.com/user-attachments/files/16629976/paper.zip)

I hope that addresses both points successfully, and will close the issue, but do shout if you would like me to reopen it!
