### ISSUE TITLE
 New features: Ecosystem engineering

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#7]
This section strikes a much better balance between clarity and context.  The one aspect that could use additional explanation is what it means for the genome of an organism to be added to the environment as an additional mask (line 65).  Another sentence clarifying the mathematics of how this impacts fitness scores would be helpful.

**Comment by RussellGarwood** [comment]
The above commit adds a little more explanation, which I hope helps cover these bases. There is further discussion of the implications of this distinction in the paper associated with the addition of EE, FYI.
