### ISSUE TITLE
 New features: Expanding playing field

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#8]
I don’t understand this section. Does the “this” on line 73 refer to “this number”, “this species”, or “the playing field” grows?  If a species only contains a single individual, how does the number of species increase? If the playing field grows when species originate, and there is only one individual per species, then how is there competition between species?

**Comment by RussellGarwood** [comment]
Yes, apologies, this was altogether too terse, and as a result how this option operates was not at all clear. I have tried to improve the description with the above commit.
