### ISSUE TITLE
 New features: Logging

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#9]
It took a couple of reads for me to parse how the new logging features differ from the logging that was possible under the previous version of the software.  I think that the ability to record how values change throughout the period of a run, rather than just their final values, is the novel feature. But I wasn’t clear whether the ability to customise the file, or to record many aspects of the simulation state, is also novel.  It would be instructive to provide an example of how the new feature(s) expand the range of operations/analyses that a user can attempt.

**Comment by RussellGarwood** [comment]
I have changed the wording of this section to be more explicit about what is new with the above push.
